version: '3.8'

services:
  memory:
    build: .
    ports:
      - "4000:4000"
    environment:
      - HANZO_DISABLE_AUTH=true
      - HANZO_LLM_MODEL=${HANZO_LLM_MODEL:-gpt-3.5-turbo}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - HANZO_LLM_API_BASE=${HANZO_LLM_API_BASE}
      - HANZO_LOG_LEVEL=${HANZO_LOG_LEVEL:-INFO}
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    profiles:
      - with-cache

volumes:
  redis_data: